package org.ucombinator.jade.classfile

import com.github.javaparser.ast.type.Type
import kotlin.test.* // ktlint-disable no-wildcard-imports

object SignatureTest {

  enum class Kind { TYPE, CLASS, METHOD }

  // TODO: fix '\$' in these tests

  // Tests harvested from jdk12
  val harvestedTests = listOf<Triple<Kind, String, String>>( // ("signature type", "signature", "expected result")
    // jdk12/test/jdk/tools/jlink/plugins/SignatureParserTest.java
    Triple(Kind.TYPE, "[Ljava/lang/String;", "java.lang.String[]"),
    Triple(Kind.TYPE, "[[[[[[[[[[Ljava/lang/String;", "java.lang.String[][][][][][][][][][]"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;:Ljava/lang/Comparable<-TT;>;>(Ljava/lang/String;Ljava/lang/Class<TT;>;TT;Ljava/lang/Comparable<-TT;>;Ljava/lang/Comparable<-TT;>;ZZ)V", "T extends java.lang.Object&java.lang.Comparable<? super T>;java.lang.String,java.lang.Class<T>,T,java.lang.Comparable<? super T>,java.lang.Comparable<? super T>,boolean,boolean;void;"),
    Triple(Kind.METHOD, "(Ljava/lang/String;ZLjava/util/EventListener;TTK;)V", ";java.lang.String,boolean,java.util.EventListener,TK;void;"),
    // These are not valid type, class, or method signatures, so I am not sure why SignatureParserTest.java has them
    // Triple(Kind.TYPE, "<Y:Ljava/lang/String;>", ""),
    // Triple(Kind.TYPE, "<Y:Ljava/lang/String;Z::Ljava/util/EventListener;>", ""),
    // Triple(Kind.TYPE, "<Y:Ljava/lang/String;Z::Ljava/util/EventListener;O::Ljava/lang/Comparable<Ljava/lang/String;>;>", ""),
    // Triple(Kind.TYPE, "<Y:Ljava/lang/String;O::Ljava/lang/Comparable<Ljava/lang/String;Ljava/lang/Float;>;>", ""),
    // Triple(Kind.TYPE, "<Y:Ljava/lang/String;O::Ljava/lang/Comparable<Ljava/lang/String;Ljava/lang/Float<Ljava/lang/Object;>;>;>", ""),
    Triple(Kind.TYPE, "Ljava/util/Set;", "java.util.Set"),
    Triple(Kind.TYPE, "Ljavaapplication20/Titi<[Ljava/lang/String;Ljava/lang/Integer;>;", "javaapplication20.Titi<java.lang.String[],java.lang.Integer>"),
    Triple(Kind.TYPE, "Ljava/lang/Comparable<TK;>;", "java.lang.Comparable<K>"),
    // These are not valid type, class, or method signatures, so I am not sure why SignatureParserTest.java has them
    // Triple(Kind.TYPE, "Ljava/io/Serializable;Ljava/lang/Comparable<TK;>;", ""),
    // Triple(Kind.TYPE, "<Y:Ljava/lang/String;Z::Ljava/util/EventListener;K::Ljava/util/EventListener;O::Ljava/lang/Comparable<Ljava/lang/String;>;>Ljavaapplication20/Titi<[Ljava/lang/String;Ljava/lang/Integer;TZ;>;Ljava/io/Serializable;Ljava/lang/Comparable<TK;>;", ""),
    Triple(Kind.METHOD, "<PO:Ljava/lang/Object;>(Ljava/lang/Integer;TPO;)Ljava/lang/Integer;", "PO extends java.lang.Object;java.lang.Integer,PO;java.lang.Integer;"),
    Triple(Kind.METHOD, "<PO:Ljava/lang/Object;>(Ljava/lang/Integer;TPO;)TPO;", "PO extends java.lang.Object;java.lang.Integer,PO;PO;"),
    Triple(Kind.METHOD, "<T::Ljava/util/EventListener;>(Ljava/lang/Class<TT;>;)[TT;", "T extends java.util.EventListener;java.lang.Class<T>;T[];"),
    Triple(Kind.METHOD, "<PO:LTiti;>(Ljava/lang/Integer;ITPO;)Z", "PO extends Titi;java.lang.Integer,int,PO;boolean;"),
    Triple(Kind.CLASS, "<K:Ljava/lang/Object;V:Ljava/lang/Object;>Ljava/lang/Object;", "K extends java.lang.Object,V extends java.lang.Object;java.lang.Object;"),
    Triple(Kind.TYPE, "Ljava/util/LinkedHashMap<TK;TV;>.LinkedHashIterator;Ljava/util/Iterator<TV;>;", "java.util.LinkedHashMap<K,V>.LinkedHashIterator"),
    Triple(Kind.TYPE, "LToto<Ljava/lang/String;>;", "Toto<java.lang.String>"),
    Triple(Kind.TYPE, "Ljavaapplication20/Titi<[Ljava/lang/String;Ljava/lang/Integer<LToto;>;TZ;>;", "javaapplication20.Titi<java.lang.String[],java.lang.Integer<Toto>,Z>"),
    Triple(Kind.TYPE, "LX<[LQ;LW<LToto;>;TZ;>;", "X<Q[],W<Toto>,Z>"),
    Triple(Kind.TYPE, "Ljava/lang/String<*>;", "java.lang.String<?>"),
    Triple(Kind.TYPE, "Ljava/util/List<[B>;", "java.util.List<byte[]>"),
    Triple(Kind.CLASS, "<T:Ljava/lang/Object;T_NODE::Ljava/util/stream/Node<TT;>;>Ljava/lang/Object;Ljava/util/stream/Node<TT;>;", "T extends java.lang.Object,T_NODE extends java.util.stream.Node<T>;java.lang.Object;java.util.stream.Node<T>"),
    Triple(Kind.TYPE, "Ljavaapplication20/Titi<[Ljava/lang/String;>;", "javaapplication20.Titi<java.lang.String[]>"),
    Triple(Kind.CLASS, "<A::Ljava/lang/annotation/Annotation;W::Lcom/sun/codemodel/internal/JAnnotationWriter<TA;>;>Ljava/lang/Object;Ljava/lang/reflect/InvocationHandler;Lcom/sun/codemodel/internal/JAnnotationWriter<TA;>;", "A extends java.lang.annotation.Annotation,W extends com.sun.codemodel.internal.JAnnotationWriter<A>;java.lang.Object;java.lang.reflect.InvocationHandler,com.sun.codemodel.internal.JAnnotationWriter<A>"),
    Triple(Kind.METHOD, "<W::Lcom/sun/codemodel/internal/JAnnotationWriter<*>;>(Ljava/lang/Class<TW;>;Lcom/sun/codemodel/internal/JAnnotatable;)TW;", "W extends com.sun.codemodel.internal.JAnnotationWriter<?>;java.lang.Class<W>,com.sun.codemodel.internal.JAnnotatable;W;"),
    Triple(Kind.TYPE, "Ljava/util/Set<Lcom/sun/tools/jdeps/JdepsTask\$DotGraph<TT;>.Edge;>;", "java.util.Set<com.sun.tools.jdeps.JdepsTask\$DotGraph<T>.Edge>"),
    Triple(Kind.CLASS, "<E::Lcom/sun/xml/internal/rngom/ast/om/ParsedElementAnnotation;L::Lcom/sun/xml/internal/rngom/ast/om/Location;CL::Lcom/sun/xml/internal/rngom/ast/builder/CommentList<TL;>;>Ljava/lang/Object;", "E extends com.sun.xml.internal.rngom.ast.om.ParsedElementAnnotation,L extends com.sun.xml.internal.rngom.ast.om.Location,CL extends com.sun.xml.internal.rngom.ast.builder.CommentList<L>;java.lang.Object;"),
    Triple(Kind.METHOD, "(Ljava/util/List<Lcom/sun/xml/internal/rngom/nc/NameClass;>;TL;TA;)Lcom/sun/xml/internal/rngom/nc/NameClass;", ";java.util.List<com.sun.xml.internal.rngom.nc.NameClass>,L,A;com.sun.xml.internal.rngom.nc.NameClass;"),
    Triple(Kind.TYPE, "[Ljava/util/List;", "java.util.List[]"),
    Triple(Kind.TYPE, "[Ljava/util/List<+Lcom/sun/jdi/request/EventRequest;>;", "java.util.List<? extends com.sun.jdi.request.EventRequest>[]"),
    Triple(Kind.TYPE, "Lcom/sun/xml/internal/bind/v2/util/QNameMap<TV;>.HashIterator<Lcom/sun/xml/internal/bind/v2/util/QNameMap\$Entry<TV;>;>;", "com.sun.xml.internal.bind.v2.util.QNameMap<V>.HashIterator<com.sun.xml.internal.bind.v2.util.QNameMap\$Entry<V>>"),
    Triple(Kind.TYPE, "[Ljava/lang/String;", "java.lang.String[]"),
    Triple(Kind.TYPE, "[Ljava/lang/String<Ljava/lang/Toto<Ljava/lang/Titi;>;>;", "java.lang.String<java.lang.Toto<java.lang.Titi>>[]"),
    Triple(Kind.METHOD, "<T::Ljava/util/EventListener;K:Ljava/util/BOO;>(ZCLjava/lang/Class<TT;>;IJS)[TT;", "T extends java.util.EventListener,K extends java.util.BOO;boolean,char,java.lang.Class<T>,int,long,short;T[];"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;ILjava/lang/Long;)TT;", "T extends java.lang.Object;T,int,java.lang.Long;T;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;ILjava/lang/Long;)TT;^TT;", "T extends java.lang.Object;T,int,java.lang.Long;T;T"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;ILjava/lang/Long;)TT;^TT;^Ljava/lang/Exception;", "T extends java.lang.Object;T,int,java.lang.Long;T;T,java.lang.Exception"),

    // jdk12/test/langtools/tools/javac/classfiles/attributes/Signature/ConstructorTest.java
    Triple(Kind.CLASS, "<T:Ljava/lang/Object;>Ljava/lang/Object;", "T extends java.lang.Object;java.lang.Object;"),
    Triple(Kind.METHOD, "(TT;Z)V", ";T,boolean;void;"),
    Triple(Kind.METHOD, "(TT;B)V", ";T,byte;void;"),
    Triple(Kind.METHOD, "(TT;C)V", ";T,char;void;"),
    Triple(Kind.METHOD, "(TT;S)V", ";T,short;void;"),
    Triple(Kind.METHOD, "(TT;I)V", ";T,int;void;"),
    Triple(Kind.METHOD, "(TT;J)V", ";T,long;void;"),
    Triple(Kind.METHOD, "(TT;F)V", ";T,float;void;"),
    Triple(Kind.METHOD, "(TT;D)V", ";T,double;void;"),
    Triple(Kind.METHOD, "(TT;Ljava/lang/Runnable;)V", ";T,java.lang.Runnable;void;"),
    Triple(Kind.METHOD, "(TT;[Z)V", ";T,boolean[];void;"),
    Triple(Kind.METHOD, "(TT;[B)V", ";T,byte[];void;"),
    Triple(Kind.METHOD, "(TT;[C)V", ";T,char[];void;"),
    Triple(Kind.METHOD, "(TT;[S)V", ";T,short[];void;"),
    Triple(Kind.METHOD, "(TT;[I)V", ";T,int[];void;"),
    Triple(Kind.METHOD, "(TT;[J)V", ";T,long[];void;"),
    Triple(Kind.METHOD, "(TT;[F)V", ";T,float[];void;"),
    Triple(Kind.METHOD, "(TT;[D)V", ";T,double[];void;"),
    Triple(Kind.METHOD, "(TT;[Ljava/lang/Runnable;)V", ";T,java.lang.Runnable[];void;"),
    Triple(Kind.METHOD, "([TT;)V", ";T[];void;"),
    Triple(Kind.METHOD, "<T::Ljava/lang/Runnable;>([TT;)V", "T extends java.lang.Runnable;T[];void;"),
    Triple(Kind.METHOD, "(Ljava/util/Map<**>;)V", ";java.util.Map<?,?>;void;"),
    Triple(Kind.METHOD, "(TT;)V", ";T;void;"),
    Triple(Kind.METHOD, "<E::Ljava/util/Set<+TT;>;>(TE;TE;)V", "E extends java.util.Set<? extends T>;E,E;void;"),
    Triple(Kind.METHOD, "<E:Ljava/lang/ref/ReferenceQueue<-TT;>;:Ljava/util/Map<-TT;+TT;>;>(TE;TE;)V", "E extends java.lang.ref.ReferenceQueue<? super T>&java.util.Map<? super T,? extends T>;E,E;void;"),
    Triple(Kind.METHOD, "(Ljava/util/List<+TT;>;)V", ";java.util.List<? extends T>;void;"),
    Triple(Kind.METHOD, "(Ljava/util/Set<-TT;>;)V", ";java.util.Set<? super T>;void;"),
    Triple(Kind.METHOD, "<E::Ljava/lang/Runnable;>(TE;)V", "E extends java.lang.Runnable;E;void;"),
    Triple(Kind.METHOD, "<E:TT;>(TT;TE;)V", "E extends T;T,E;void;"),
    Triple(Kind.CLASS, "Ljava/lang/Enum<LEnumTest;>;", ";java.lang.Enum<EnumTest>;"),
    Triple(Kind.METHOD, "()V", ";;void;"),

    // jdk12/test/langtools/tools/javac/classfiles/attributes/Signature/ExceptionTest.java
    Triple(Kind.CLASS, "<Exc:Ljava/lang/RuntimeException;:Ljava/lang/Runnable;>Ljava/lang/Object;", "Exc extends java.lang.RuntimeException&java.lang.Runnable;java.lang.Object;"),
    Triple(Kind.METHOD, "<E:Ljava/lang/Exception;>()V^TE;", "E extends java.lang.Exception;;void;E"),
    Triple(Kind.METHOD, "<E:Ljava/lang/Exception;>(I)V^Ljava/io/IOException;^TE;^Ljava/io/IOError;", "E extends java.lang.Exception;int;void;java.io.IOException,E,java.io.IOError"),
    Triple(Kind.METHOD, "(J)V^TExc;", ";long;void;Exc"),
    Triple(Kind.METHOD, "(B)V^Ljava/io/IOError;^TExc;^Ljava/io/IOException;", ";byte;void;java.io.IOError,Exc,java.io.IOException"),
    Triple(Kind.METHOD, "(TExc;)V", ";Exc;void;"),
    Triple(Kind.METHOD, "(I)V^TExc;", ";int;void;Exc"),
    Triple(Kind.METHOD, "(J)V^TExc;^Ljava/io/IOException;", ";long;void;Exc,java.io.IOException"),
    Triple(Kind.METHOD, "(TExc;)V", ";Exc;void;"),
    Triple(Kind.METHOD, "<E:Ljava/lang/Exception;:Ljava/lang/Runnable;>(I)V^TE;", "E extends java.lang.Exception&java.lang.Runnable;int;void;E"),
    Triple(Kind.METHOD, "<E:Ljava/lang/Exception;>(J)V^Ljava/io/IOError;^TE;^Ljava/io/IOException;", "E extends java.lang.Exception;long;void;java.io.IOError,E,java.io.IOException"),
    Triple(Kind.METHOD, "<E:Ljava/lang/Exception;>(TE;)V", "E extends java.lang.Exception;E;void;"),

    // jdk12/test/langtools/tools/javac/classfiles/attributes/Signature/FieldTest.java
    Triple(Kind.CLASS, "<T:Ljava/lang/Object;>Ljava/lang/Object;", "T extends java.lang.Object;java.lang.Object;"),
    Triple(Kind.TYPE, "Ljava/util/List<TT;>;", "java.util.List<T>"),
    Triple(Kind.TYPE, "Ljava/util/List<Ljava/util/Map<+TT;-TT;>;>;", "java.util.List<java.util.Map<? extends T,? super T>>"),
    Triple(Kind.TYPE, "TT;", "T"),
    Triple(Kind.TYPE, "[TT;", "T[]"),
    Triple(Kind.TYPE, "Ljava/util/List<[B>;", "java.util.List<byte[]>"),
    Triple(Kind.TYPE, "Ljava/util/List<[S>;", "java.util.List<short[]>"),
    Triple(Kind.TYPE, "Ljava/util/List<[I>;", "java.util.List<int[]>"),
    Triple(Kind.TYPE, "Ljava/util/List<[J>;", "java.util.List<long[]>"),
    Triple(Kind.TYPE, "Ljava/util/List<[C>;", "java.util.List<char[]>"),
    Triple(Kind.TYPE, "Ljava/util/List<[Z>;", "java.util.List<boolean[]>"),
    Triple(Kind.TYPE, "Ljava/util/List<[F>;", "java.util.List<float[]>"),
    Triple(Kind.TYPE, "Ljava/util/List<[D>;", "java.util.List<double[]>"),
    Triple(Kind.TYPE, "Ljava/util/List<Ljava/lang/Integer;>;", "java.util.List<java.lang.Integer>"),
    Triple(Kind.TYPE, "[[TT;", "T[][]"),
    Triple(Kind.TYPE, "[Ljava/util/List<TT;>;", "java.util.List<T>[]"),
    Triple(Kind.TYPE, "Ljava/util/List<+TT;>;", "java.util.List<? extends T>"),
    Triple(Kind.TYPE, "Ljava/util/Comparator<-TT;>;", "java.util.Comparator<? super T>"),
    Triple(Kind.TYPE, "Ljava/util/List<+Ljava/util/Comparator<-TT;>;>;", "java.util.List<? extends java.util.Comparator<? super T>>"),
    Triple(Kind.TYPE, "Ljava/util/Comparator<*>;", "java.util.Comparator<?>"),
    Triple(Kind.TYPE, "Ljava/util/Map<+[Z-[Z>;", "java.util.Map<? extends boolean[],? super boolean[]>"),
    Triple(Kind.TYPE, "Ljava/util/Map<+[B-[B>;", "java.util.Map<? extends byte[],? super byte[]>"),
    Triple(Kind.TYPE, "Ljava/util/Map<+[S-[S>;", "java.util.Map<? extends short[],? super short[]>"),
    Triple(Kind.TYPE, "Ljava/util/Map<+[I-[I>;", "java.util.Map<? extends int[],? super int[]>"),
    Triple(Kind.TYPE, "Ljava/util/Map<+[J-[J>;", "java.util.Map<? extends long[],? super long[]>"),
    Triple(Kind.TYPE, "Ljava/util/Map<+[C-[C>;", "java.util.Map<? extends char[],? super char[]>"),
    Triple(Kind.TYPE, "Ljava/util/Map<+[F-[F>;", "java.util.Map<? extends float[],? super float[]>"),
    Triple(Kind.TYPE, "Ljava/util/Map<+[D-[D>;", "java.util.Map<? extends double[],? super double[]>"),
    Triple(Kind.TYPE, "Ljava/util/Map<+[Ljava/lang/Object;-[Ljava/lang/Object;>;", "java.util.Map<? extends java.lang.Object[],? super java.lang.Object[]>"),

    // jdk12/test/langtools/tools/javac/classfiles/attributes/Signature/InnerClassTest.java
    Triple(Kind.CLASS, "<T:Ljava/util/ArrayList<TT;>;:Ljava/lang/Runnable;>Ljava/lang/Object;", "T extends java.util.ArrayList<T>&java.lang.Runnable;java.lang.Object;"),
    Triple(Kind.CLASS, "LInnerClassTest\$1Local1;", ";InnerClassTest\$1Local1;"),
    Triple(Kind.CLASS, "LInnerClassTest\$1Local2<Ljava/util/ArrayList<TT;>;Ljava/util/Map<Ljava/util/ArrayList<TT;>;Ljava/util/ArrayList<TT;>;>;>;", ";InnerClassTest\$1Local2<java.util.ArrayList<T>,java.util.Map<java.util.ArrayList<T>,java.util.ArrayList<T>>>;"),
    Triple(Kind.TYPE, "TT;", "T"),
    Triple(Kind.TYPE, "[TT;", "T[]"),
    Triple(Kind.CLASS, "<T:Ljava/lang/Object;U::Ljava/util/Map<+TT;-TT;>;>Ljava/lang/Object;", "T extends java.lang.Object,U extends java.util.Map<? extends T,? super T>;java.lang.Object;"),
    Triple(Kind.METHOD, "(TT;TU;)V", ";T,U;void;"),
    Triple(Kind.METHOD, "([TT;)[TU;", ";T[];U[];"),
    Triple(Kind.CLASS, "LInnerClassTest\$1Local2<Ljava/util/ArrayList<TT;>;Ljava/util/Map<Ljava/util/ArrayList<TT;>;Ljava/util/ArrayList<TT;>;>;>;", ";InnerClassTest\$1Local2<java.util.ArrayList<T>,java.util.Map<java.util.ArrayList<T>,java.util.ArrayList<T>>>;"),
    Triple(Kind.TYPE, "TT;", "T"),
    Triple(Kind.TYPE, "[TT;", "T[]"),
    Triple(Kind.CLASS, "<E:TT;U::Ljava/util/Set<-TE;>;>Ljava/lang/Object;", "E extends T,U extends java.util.Set<? super E>;java.lang.Object;"),
    Triple(Kind.TYPE, "[TT;", "T[]"),
    Triple(Kind.TYPE, "Ljava/util/List<+TT;>;", "java.util.List<? extends T>"),
    Triple(Kind.TYPE, "Ljava/util/List<-TU;>;", "java.util.List<? super U>"),
    Triple(Kind.TYPE, "Ljava/util/List<*>;", "java.util.List<?>"),
    Triple(Kind.TYPE, "Ljava/util/List<Ljava/lang/Integer;>;", "java.util.List<java.lang.Integer>"),
    Triple(Kind.TYPE, "Ljava/util/List<TE;>;", "java.util.List<E>"),
    Triple(Kind.METHOD, "(TT;)V", ";T;void;"),
    Triple(Kind.METHOD, "(TT;TE;)V", ";T,E;void;"),
    Triple(Kind.METHOD, "(TT;)TE;", ";T;E;"),
    Triple(Kind.CLASS, "<T:Ljava/lang/Object;>Ljava/lang/Object;", "T extends java.lang.Object;java.lang.Object;"),
    Triple(Kind.METHOD, "(TT;)TT;", ";T;T;"),
    Triple(Kind.TYPE, "Ljava/util/List<+Ljava/lang/Number;>;", "java.util.List<? extends java.lang.Number>"),
    Triple(Kind.TYPE, "Ljava/util/List<-Ljava/lang/Number;>;", "java.util.List<? super java.lang.Number>"),
    Triple(Kind.TYPE, "Ljava/util/List<*>;", "java.util.List<?>"),
    Triple(Kind.TYPE, "Ljava/util/List<Ljava/lang/Integer;>;", "java.util.List<java.lang.Integer>"),
    Triple(Kind.METHOD, "(Ljava/util/List<-TT;>;)Ljava/util/List<+TT;>;", ";java.util.List<? super T>;java.util.List<? extends T>;"),
    Triple(Kind.METHOD, "(Ljava/util/List<+TT;>;)Ljava/util/List<-TT;>;", ";java.util.List<? extends T>;java.util.List<? super T>;"),
    Triple(Kind.METHOD, "(Ljava/util/Map<**>;)Ljava/util/Map<**>;", ";java.util.Map<?,?>;java.util.Map<?,?>;"),
    Triple(Kind.METHOD, "(Ljava/util/List<+TT;>;Ljava/util/List<-TT;>;Ljava/util/Map<**>;)Ljava/util/List<*>;", ";java.util.List<? extends T>,java.util.List<? super T>,java.util.Map<?,?>;java.util.List<?>;"),
    Triple(Kind.METHOD, "<T::Ljava/lang/Runnable;>(Ljava/util/List<+TT;>;Ljava/util/List<-TT;>;Ljava/util/Map<**>;)Ljava/util/List<*>;", "T extends java.lang.Runnable;java.util.List<? extends T>,java.util.List<? super T>,java.util.Map<?,?>;java.util.List<?>;"),
    Triple(Kind.CLASS, "LInnerClassTest<TT;>.InnerClass1<TT;Ljava/util/Set<TT;>;>;LInnerClassTest\$InnerInterface<TT;>;", ";InnerClassTest<T>.InnerClass1<T,java.util.Set<T>>;InnerClassTest\$InnerInterface<T>"),
    Triple(Kind.METHOD, "(TT;)V", ";T;void;"),
    Triple(Kind.METHOD, "(TT;TT;)V", ";T,T;void;"),
    Triple(Kind.METHOD, "(TT;)TT;", ";T;T;"),
    Triple(Kind.METHOD, "(Ljava/util/List<-TT;>;)Ljava/util/List<+TT;>;", ";java.util.List<? super T>;java.util.List<? extends T>;"),
    Triple(Kind.METHOD, "(Ljava/util/List<+TT;>;)Ljava/util/List<-TT;>;", ";java.util.List<? extends T>;java.util.List<? super T>;"),
    Triple(Kind.METHOD, "(Ljava/util/Map<**>;)Ljava/util/Map<**>;", ";java.util.Map<?,?>;java.util.Map<?,?>;"),
    Triple(Kind.CLASS, "<T:Ljava/lang/String;E::Ljava/util/Set<TT;>;>Ljava/lang/Object;LInnerClassTest\$InnerInterface<TE;>;", "T extends java.lang.String,E extends java.util.Set<T>;java.lang.Object;InnerClassTest\$InnerInterface<E>"),
    Triple(Kind.METHOD, "<E::Ljava/lang/Runnable;>(TE;)V", "E extends java.lang.Runnable;E;void;"),
    Triple(Kind.METHOD, "(TT;)V", ";T;void;"),
    Triple(Kind.METHOD, "(TT;TE;)V", ";T,E;void;"),
    Triple(Kind.TYPE, "Ljava/util/List<+Ljava/lang/Number;>;", "java.util.List<? extends java.lang.Number>"),
    Triple(Kind.TYPE, "Ljava/util/List<-Ljava/lang/Number;>;", "java.util.List<? super java.lang.Number>"),
    Triple(Kind.TYPE, "Ljava/util/List<*>;", "java.util.List<?>"),
    Triple(Kind.TYPE, "Ljava/util/List<Ljava/lang/Integer;>;", "java.util.List<java.lang.Integer>"),
    Triple(Kind.METHOD, "(TE;)TE;", ";E;E;"),
    Triple(Kind.METHOD, "(Ljava/util/List<-TE;>;)Ljava/util/List<+TE;>;", ";java.util.List<? super E>;java.util.List<? extends E>;"),
    Triple(Kind.METHOD, "(Ljava/util/List<+TE;>;)Ljava/util/List<-TE;>;", ";java.util.List<? extends E>;java.util.List<? super E>;"),
    Triple(Kind.METHOD, "(Ljava/util/Map<**>;)Ljava/util/Map<**>;", ";java.util.Map<?,?>;java.util.Map<?,?>;"),
    Triple(Kind.METHOD, "<E:Ljava/lang/Object;>(TE;)TE;", "E extends java.lang.Object;E;E;"),
    Triple(Kind.METHOD, "<E:Ljava/lang/Object;>(Ljava/util/List<-TE;>;)Ljava/util/List<+TE;>;", "E extends java.lang.Object;java.util.List<? super E>;java.util.List<? extends E>;"),
    Triple(Kind.METHOD, "<E:Ljava/lang/Object;>(Ljava/util/List<+TE;>;)Ljava/util/List<-TE;>;", "E extends java.lang.Object;java.util.List<? extends E>;java.util.List<? super E>;"),
    Triple(Kind.METHOD, "<E:Ljava/lang/Object;>(Ljava/util/Map<**>;)Ljava/util/Map<**>;", "E extends java.lang.Object;java.util.Map<?,?>;java.util.Map<?,?>;"),
    Triple(Kind.CLASS, "Ljava/lang/Object;LInnerClassTest\$ExceptionHolder<Ljava/lang/RuntimeException;>;Ljava/util/concurrent/Callable<Ljava/util/Map<**>;>;", ";java.lang.Object;InnerClassTest\$ExceptionHolder<java.lang.RuntimeException>,java.util.concurrent.Callable<java.util.Map<?,?>>"),
    Triple(Kind.METHOD, "()Ljava/util/Map<**>;", ";;java.util.Map<?,?>;"),
    Triple(Kind.CLASS, "<E:Ljava/lang/Exception;>Ljava/lang/Object;", "E extends java.lang.Exception;java.lang.Object;"),
    Triple(Kind.METHOD, "()V^TE;", ";;void;E"),
    Triple(Kind.METHOD, "()TE;", ";;E;"),

    // jdk12/test/langtools/tools/javac/classfiles/attributes/Signature/MethodParameterTest.java
    Triple(Kind.CLASS, "<T:Ljava/lang/Object;>Ljava/lang/Object;", "T extends java.lang.Object;java.lang.Object;"),
    Triple(Kind.METHOD, "<E:TT;U::Ljava/util/List<TE;>;:Ljava/lang/Runnable;>(TT;Ljava/util/Set<-TE;>;Ljava/util/ArrayList<+Ljava/util/Set<TU;>;>;)V", "E extends T,U extends java.util.List<E>&java.lang.Runnable;T,java.util.Set<? super E>,java.util.ArrayList<? extends java.util.Set<U>>;void;"),
    Triple(Kind.METHOD, "<E:TT;U::Ljava/util/List<TE;>;:Ljava/lang/Runnable;>(TT;TU;Ljava/util/ArrayList<+Ljava/util/Set<TU;>;>;)V", "E extends T,U extends java.util.List<E>&java.lang.Runnable;T,U,java.util.ArrayList<? extends java.util.Set<U>>;void;"),
    Triple(Kind.METHOD, "<T::Ljava/util/List<*>;E::Ljava/util/Set<-TT;>;>(TE;[TT;Ljava/util/Map<*+TE;>;)TE;", "T extends java.util.List<?>,E extends java.util.Set<? super T>;E,T[],java.util.Map<?,? extends E>;E;"),
    Triple(Kind.METHOD, "(TT;[Z)V", ";T,boolean[];void;"),
    Triple(Kind.METHOD, "(TT;[C)V", ";T,char[];void;"),
    Triple(Kind.METHOD, "(TT;[B)V", ";T,byte[];void;"),
    Triple(Kind.METHOD, "(TT;[S)V", ";T,short[];void;"),
    Triple(Kind.METHOD, "(TT;[I)V", ";T,int[];void;"),
    Triple(Kind.METHOD, "(TT;[J)V", ";T,long[];void;"),
    Triple(Kind.METHOD, "(TT;[F)V", ";T,float[];void;"),
    Triple(Kind.METHOD, "(TT;[D)V", ";T,double[];void;"),
    Triple(Kind.METHOD, "(TT;[Ljava/lang/Object;)V", ";T,java.lang.Object[];void;"),
    Triple(Kind.METHOD, "([TT;)V", ";T[];void;"),
    Triple(Kind.METHOD, "(TT;[Z)V", ";T,boolean[];void;"),
    Triple(Kind.METHOD, "(TT;[C)V", ";T,char[];void;"),
    Triple(Kind.METHOD, "(TT;[B)V", ";T,byte[];void;"),
    Triple(Kind.METHOD, "(TT;[S)V", ";T,short[];void;"),
    Triple(Kind.METHOD, "(TT;[I)V", ";T,int[];void;"),
    Triple(Kind.METHOD, "(TT;[J)V", ";T,long[];void;"),
    Triple(Kind.METHOD, "(TT;[F)V", ";T,float[];void;"),
    Triple(Kind.METHOD, "(TT;[D)V", ";T,double[];void;"),
    Triple(Kind.METHOD, "(TT;[Ljava/lang/Object;)V", ";T,java.lang.Object[];void;"),
    Triple(Kind.METHOD, "([TT;)V", ";T[];void;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;[Z)V", "T extends java.lang.Object;T,boolean[];void;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;[C)V", "T extends java.lang.Object;T,char[];void;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;[B)V", "T extends java.lang.Object;T,byte[];void;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;[S)V", "T extends java.lang.Object;T,short[];void;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;[I)V", "T extends java.lang.Object;T,int[];void;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;[J)V", "T extends java.lang.Object;T,long[];void;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;[F)V", "T extends java.lang.Object;T,float[];void;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;[D)V", "T extends java.lang.Object;T,double[];void;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;[Ljava/lang/Object;)V", "T extends java.lang.Object;T,java.lang.Object[];void;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>([TT;)V", "T extends java.lang.Object;T[];void;"),

    // jdk12/test/langtools/tools/javac/classfiles/attributes/Signature/MethodTypeBoundTest.java
    Triple(Kind.CLASS, "<T:Ljava/lang/Object;>Ljava/lang/Object;", "T extends java.lang.Object;java.lang.Object;"),
    Triple(Kind.METHOD, "<E:Ljava/lang/String;:Ljava/lang/Runnable;:Ljava/util/Collection<+TT;>;>(TE;)TE;", "E extends java.lang.String&java.lang.Runnable&java.util.Collection<? extends T>;E;E;"),
    Triple(Kind.METHOD, "<E::Ljava/lang/Runnable;:Ljava/util/Collection<-TT;>;>(TE;)TE;", "E extends java.lang.Runnable&java.util.Collection<? super T>;E;E;"),
    Triple(Kind.METHOD, "<E:Ljava/util/ArrayList<+TT;>;>(TE;)TE;", "E extends java.util.ArrayList<? extends T>;E;E;"),
    Triple(Kind.METHOD, "<E:Ljava/util/LinkedList<TE;>;:Ljava/util/List<TE;>;>(TE;)TE;", "E extends java.util.LinkedList<E>&java.util.List<E>;E;E;"),
    Triple(Kind.METHOD, "<E:Ljava/util/LinkedList<TE;>;:Ljava/util/List<TE;>;U::Ljava/util/Iterator<-LMethodTypeBoundTest<TT;>.InnerClass<TE;>;>;>(TU;)TE;", "E extends java.util.LinkedList<E>&java.util.List<E>,U extends java.util.Iterator<? super MethodTypeBoundTest<T>.InnerClass<E>>;U;E;"),
    Triple(Kind.METHOD, "<E:Ljava/util/LinkedList<TT;>;U:TE;>()V", "E extends java.util.LinkedList<T>,U extends E;;void;"),
    Triple(Kind.CLASS, "<T:Ljava/lang/Object;>Ljava/lang/Object;", "T extends java.lang.Object;java.lang.Object;"),

    // jdk12/test/langtools/tools/javac/classfiles/attributes/Signature/ReturnTypeTest.java
    Triple(Kind.CLASS, "<T:Ljava/awt/Frame;:Ljava/lang/Runnable;:Ljava/util/concurrent/Callable<[TT;>;>Ljava/lang/Object;", "T extends java.awt.Frame&java.lang.Runnable&java.util.concurrent.Callable<T[]>;java.lang.Object;"),
    Triple(Kind.METHOD, "(TT;)[B", ";T;byte[];"),
    Triple(Kind.METHOD, "(TT;)[S", ";T;short[];"),
    Triple(Kind.METHOD, "(TT;)[C", ";T;char[];"),
    Triple(Kind.METHOD, "(TT;)[I", ";T;int[];"),
    Triple(Kind.METHOD, "(TT;)[J", ";T;long[];"),
    Triple(Kind.METHOD, "(TT;)[Z", ";T;boolean[];"),
    Triple(Kind.METHOD, "(TT;)[F", ";T;float[];"),
    Triple(Kind.METHOD, "(TT;)[D", ";T;double[];"),
    Triple(Kind.METHOD, "(TT;)[Ljava/lang/Object;", ";T;java.lang.Object[];"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)[B", "T extends java.lang.Object;T;byte[];"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)[S", "T extends java.lang.Object;T;short[];"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)[C", "T extends java.lang.Object;T;char[];"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)[I", "T extends java.lang.Object;T;int[];"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)[J", "T extends java.lang.Object;T;long[];"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)[Z", "T extends java.lang.Object;T;boolean[];"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)[F", "T extends java.lang.Object;T;float[];"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)[D", "T extends java.lang.Object;T;double[];"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)[Ljava/lang/Object;", "T extends java.lang.Object;T;java.lang.Object[];"),
    Triple(Kind.METHOD, "()TT;", ";;T;"),
    Triple(Kind.METHOD, "()[TT;", ";;T[];"),
    Triple(Kind.METHOD, "<E:TT;>()TE;", "E extends T;;E;"),
    Triple(Kind.METHOD, "<E:TT;>()[TE;", "E extends T;;E[];"),
    Triple(Kind.METHOD, "()Ljava/util/List<TT;>;", ";;java.util.List<T>;"),
    Triple(Kind.METHOD, "()[Ljava/util/List<TT;>;", ";;java.util.List<T>[];"),
    Triple(Kind.METHOD, "()Ljava/util/List<+TT;>;", ";;java.util.List<? extends T>;"),
    Triple(Kind.METHOD, "()[Ljava/util/List<+TT;>;", ";;java.util.List<? extends T>[];"),
    Triple(Kind.METHOD, "()Ljava/util/List<-TT;>;", ";;java.util.List<? super T>;"),
    Triple(Kind.METHOD, "()[Ljava/util/List<-TT;>;", ";;java.util.List<? super T>[];"),
    Triple(Kind.METHOD, "()Ljava/util/Map<**>;", ";;java.util.Map<?,?>;"),
    Triple(Kind.METHOD, "()[Ljava/util/Map<**>;", ";;java.util.Map<?,?>[];"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>()TT;", "T extends java.lang.Object;;T;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>()[TT;", "T extends java.lang.Object;;T[];"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;E:TT;>()TE;", "T extends java.lang.Object,E extends T;;E;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;E:TT;>()[TE;", "T extends java.lang.Object,E extends T;;E[];"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>()Ljava/util/List<TT;>;", "T extends java.lang.Object;;java.util.List<T>;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>()[Ljava/util/List<TT;>;", "T extends java.lang.Object;;java.util.List<T>[];"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>()Ljava/util/List<+TT;>;", "T extends java.lang.Object;;java.util.List<? extends T>;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>()[Ljava/util/List<+TT;>;", "T extends java.lang.Object;;java.util.List<? extends T>[];"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>()Ljava/util/List<-TT;>;", "T extends java.lang.Object;;java.util.List<? super T>;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>()[Ljava/util/List<-TT;>;", "T extends java.lang.Object;;java.util.List<? super T>[];"),
    Triple(Kind.METHOD, "()Ljava/util/Map<**>;", ";;java.util.Map<?,?>;"),
    Triple(Kind.METHOD, "()[Ljava/util/Map<**>;", ";;java.util.Map<?,?>[];"),
    Triple(Kind.METHOD, "()Ljava/util/Map<+[Z-[Z>;", ";;java.util.Map<? extends boolean[],? super boolean[]>;"),
    Triple(Kind.METHOD, "()Ljava/util/Map<+[B-[B>;", ";;java.util.Map<? extends byte[],? super byte[]>;"),
    Triple(Kind.METHOD, "()Ljava/util/Map<+[S-[S>;", ";;java.util.Map<? extends short[],? super short[]>;"),
    Triple(Kind.METHOD, "()Ljava/util/Map<+[I-[I>;", ";;java.util.Map<? extends int[],? super int[]>;"),
    Triple(Kind.METHOD, "()Ljava/util/Map<+[J-[J>;", ";;java.util.Map<? extends long[],? super long[]>;"),
    Triple(Kind.METHOD, "()Ljava/util/Map<+[C-[C>;", ";;java.util.Map<? extends char[],? super char[]>;"),
    Triple(Kind.METHOD, "()Ljava/util/Map<+[F-[F>;", ";;java.util.Map<? extends float[],? super float[]>;"),
    Triple(Kind.METHOD, "()Ljava/util/Map<+[D-[D>;", ";;java.util.Map<? extends double[],? super double[]>;"),
    Triple(Kind.METHOD, "()Ljava/util/Map<+[Ljava/lang/Object;-[Ljava/lang/Object;>;", ";;java.util.Map<? extends java.lang.Object[],? super java.lang.Object[]>;"),
    Triple(Kind.METHOD, "(TT;)V", ";T;void;"),
    Triple(Kind.METHOD, "(TT;)B", ";T;byte;"),
    Triple(Kind.METHOD, "(TT;)S", ";T;short;"),
    Triple(Kind.METHOD, "(TT;)C", ";T;char;"),
    Triple(Kind.METHOD, "(TT;)I", ";T;int;"),
    Triple(Kind.METHOD, "(TT;)J", ";T;long;"),
    Triple(Kind.METHOD, "(TT;)Z", ";T;boolean;"),
    Triple(Kind.METHOD, "(TT;)F", ";T;float;"),
    Triple(Kind.METHOD, "(TT;)D", ";T;double;"),
    Triple(Kind.METHOD, "(TT;)Ljava/lang/Object;", ";T;java.lang.Object;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)V", "T extends java.lang.Object;T;void;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)B", "T extends java.lang.Object;T;byte;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)S", "T extends java.lang.Object;T;short;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)C", "T extends java.lang.Object;T;char;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)I", "T extends java.lang.Object;T;int;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)J", "T extends java.lang.Object;T;long;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)Z", "T extends java.lang.Object;T;boolean;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)F", "T extends java.lang.Object;T;float;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)D", "T extends java.lang.Object;T;double;"),
    Triple(Kind.METHOD, "<T:Ljava/lang/Object;>(TT;)Ljava/lang/Object;", "T extends java.lang.Object;T;java.lang.Object;"),
  )

  // TODO: ktlint: <T: Type>
  fun <T : Type> resultsToString(r: List<T>): String = r.joinToString(",") { it.asString() }
  @Test fun `harvested signatures`() {
    for ((kind, signature, expectedResult) in harvestedTests) {
      expect(expectedResult) {
        when (kind) {
          Kind.TYPE -> Signature.typeSignature(signature).asString()
          Kind.CLASS -> {
            val s = Signature.classSignature(signature)
            listOf(
              resultsToString(s.first),
              s.second.asString(),
              resultsToString(s.third),
            ).joinToString(";")
          }
          Kind.METHOD -> {
            val s = Signature.methodSignature(signature)
            listOf(
              resultsToString(s._1),
              resultsToString(s._2),
              s._3.asString(),
              resultsToString(s._4),
            ).joinToString(";")
          }
        }
      }
    }
  }
}
