site_name: Jade
site_description: A Java decompiler that aims for high reliability through extensive testing.
site_url: https://plilab.github.io/jade/
repo_url: https://github.com/plilab/jade
repo_name: plilab/jade

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist

nav:
  - Home: index.md
  - User Guide:
      - Usage: USAGE.md
      - FAQ: FAQ.md
  - Developer Guide:
      - Overview: developer-guide.md
      - Algorithms: algorithms.md
      - Projects: projects.md
      - Style: style.md
  - Testing:
      - Maven Development: maven.md
  - Miscellaneous:
      - Links: links.md
      - Notes: NOTES.md
      - TODO: TODO.md
      - Ideas: ideas.md
